name: build

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        arch:
          - amd64
          - amd64_x86
    steps:
      - uses: actions/checkout@v2
      - name: prepare msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: build programs
        run: nmake
        env:
          ARCH_NAME: _${{ matrix.arch }}

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: seika-dll-binaries-${{ matrix.arch }}
          path: |
            *.dll
            *.exe
            seika.h
            readme.md

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch artifacts for release
        uses: actions/download-artifact@v2

      - name: make zip
        run: |
          zip -r seika-dll-binaries-amd64.zip seika-dll-binaries-amd64
          zip -r seika-dll-binaries-amd64_x86.zip seika-dll-binaries-amd64_x86

      - name: generate changelog
        run: |
          PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n 2p)
          echo "PREVIOUS_TAG: $PREVIOUS_TAG"
          git log --oneline --pretty=tformat:"%h %s" $PREVIOUS_TAG..${{ github.ref }} >changelog.md
          echo "Generated changelog."

      - name: publish automatic release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "seika-dll-binaries-amd64.zip,seika-dll-binaries-amd64_x86.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "changelog.md"
