name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        arch:
          - amd64
          - amd64_x86
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: build programs
        run: nmake

      - uses: actions/upload-artifact@v2
        with:
          name: seika-dll-binaries
          path: |
            *.dll
            *.exe

      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "*.dll,*.exe,seika.h"
          token: ${{ secrets.GITHUB_TOKEN }}
